# Generated by Django 4.1.3 on 2022-11-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='endImage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
