# Generated by Django 4.1.3 on 2022-11-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicacao_endimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacao',
            name='comentarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.comentarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='endImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
