# Generated by Django 4.1.3 on 2022-11-05 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicacao_categoria_publicacao_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='publicacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.publicacao'),
            preserve_default=False,
        ),
    ]
