# Generated by Django 4.1.2 on 2022-11-05 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_publicacao_comentarios_comentarios_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.publicacao'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.categoria'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
